name: CI Atlas Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  # -----------------------------------------------------
  # 1. CORE: COMPILACIÓN Y PRUEBAS UNITARIAS
  # -----------------------------------------------------
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout del código
      uses: actions/checkout@v4

    - name: ⚙️ Configurar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 📦 Restaurar dependencias
      run: dotnet restore Atlas.sln

    - name: 🔨 Compilar el proyecto
      run: dotnet build Atlas.sln --configuration Release --no-restore

    - name: 🧪 Ejecutar Pruebas Unitarias y e2e
      run: dotnet test Atlas.sln --configuration Release --no-build --verbosity normal

  # -----------------------------------------------------
  # 2. SECOPS: SAST, SCA Y ESCANEO DE CONTENEDORES
  # -----------------------------------------------------
  security-scans:
    needs: build-and-test # Solo se ejecuta si el código compila y pasa las pruebas
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Necesario para CodeQL y Trivy
    
    steps:
    - name: 📥 Checkout del código
      uses: actions/checkout@v4

    # A. SAST (Static Application Security Testing) con CodeQL
    - name: 🛡️ Inicializar CodeQL (SAST)
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    - name: 🔨 CodeQL Auto-Build
      uses: github/codeql-action/autobuild@v3

    - name: 🔍 Analizar con CodeQL
      uses: github/codeql-action/analyze@v3

    # B. SCA & Container Scan con Trivy
    - name: 🐳 Construir imagen Docker local para escaneo
      working-directory: ./src/Atlas.Api
      run: docker build -t atlas-api:local .

    - name: 🕵️‍♂️ Escaneo de Vulnerabilidades Docker y SCA (Trivy)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'atlas-api:local'
        format: 'table'
        exit-code: '1' # Falla el pipeline si encuentra vulnerabilidades críticas
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'